"""empty message

Revision ID: 266c97d2bcf9
Revises: a6329fcdccba
Create Date: 2017-11-28 14:03:44.710003

"""

# revision identifiers, used by Alembic.
revision = '266c97d2bcf9'
down_revision = 'a6329fcdccba'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('body_html', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'body_html')
    # ### end Alembic commands ###
