"""empty message

Revision ID: 57d0abd64ac2
Revises: None
Create Date: 2017-11-24 13:30:43.962889

"""

# revision identifiers, used by Alembic.
revision = '57d0abd64ac2'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('y1', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'y1')
    # ### end Alembic commands ###
