"""empty message

Revision ID: 66b260737dbc
Revises: 4b754e76ffe5
Create Date: 2017-11-30 20:04:21.275891

"""

# revision identifiers, used by Alembic.
revision = '66b260737dbc'
down_revision = '4b754e76ffe5'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('id', sa.Integer(), nullable=False))
    op.alter_column('comments', 'post_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    op.alter_column('comments', 'user_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('comments', 'user_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    op.alter_column('comments', 'post_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    op.drop_column('comments', 'id')
    # ### end Alembic commands ###
