"""empty message

Revision ID: 704c9b1b4e13
Revises: b0ac30bfba1b
Create Date: 2017-11-24 13:37:35.151698

"""

# revision identifiers, used by Alembic.
revision = '704c9b1b4e13'
down_revision = 'b0ac30bfba1b'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'confirm2')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('confirm2', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
