"""empty message

Revision ID: 778b3bc0183d
Revises: deb41192e0fd
Create Date: 2017-11-24 13:39:28.722624

"""

# revision identifiers, used by Alembic.
revision = '778b3bc0183d'
down_revision = 'deb41192e0fd'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'confirmed')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('confirmed', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
