"""empty message

Revision ID: 7a921623362c
Revises: 22b1a04ba0ea
Create Date: 2017-11-25 11:15:37.912609

"""

# revision identifiers, used by Alembic.
revision = '7a921623362c'
down_revision = '22b1a04ba0ea'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('role_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'users', 'roles', ['role_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'role_id')
    # ### end Alembic commands ###
