"""empty message

Revision ID: 817d08946b81
Revises: 778b3bc0183d
Create Date: 2017-11-24 13:39:38.485539

"""

# revision identifiers, used by Alembic.
revision = '817d08946b81'
down_revision = '778b3bc0183d'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('confirmed', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'confirmed')
    # ### end Alembic commands ###
