"""empty message

Revision ID: 86852e7494f2
Revises: 57d0abd64ac2
Create Date: 2017-11-24 13:34:52.090666

"""

# revision identifiers, used by Alembic.
revision = '86852e7494f2'
down_revision = '57d0abd64ac2'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'y1')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('y1', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
