"""empty message

Revision ID: a6329fcdccba
Revises: c777d6f007ee
Create Date: 2017-11-25 20:45:22.081256

"""

# revision identifiers, used by Alembic.
revision = 'a6329fcdccba'
down_revision = 'c777d6f007ee'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('avatar', sa.String(length=128), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'avatar')
    # ### end Alembic commands ###
