"""empty message

Revision ID: b0ac30bfba1b
Revises: 86852e7494f2
Create Date: 2017-11-24 13:36:51.752126

"""

# revision identifiers, used by Alembic.
revision = 'b0ac30bfba1b'
down_revision = '86852e7494f2'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('confirm2', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'confirm2')
    # ### end Alembic commands ###
