"""empty message

Revision ID: deb41192e0fd
Revises: 704c9b1b4e13
Create Date: 2017-11-24 13:37:55.096430

"""

# revision identifiers, used by Alembic.
revision = 'deb41192e0fd'
down_revision = '704c9b1b4e13'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('confirmed', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'confirmed')
    # ### end Alembic commands ###
